Account available AZs: ['eu-west-1a', 'eu-west-1b', 'eu-west-1c']
Using AZs: ['eu-west-1a', 'eu-west-1b', 'eu-west-1c']
Resources:
  ClusterServiceRoleBFF38747:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: eks.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/AmazonEKSClusterPolicy
      Tags:
        - Key: Environment
          Value: Production
        - Key: Project
          Value: SwisscomAssessment
    Metadata:
      aws:cdk:path: ClusterStack/ClusterServiceRole/Resource
  Kubectl85A5A23F:
    Type: AWS::Lambda::LayerVersion
    Properties:
      Content:
        S3Bucket: cdk-hnb659fds-assets-737247133878-eu-west-1
        S3Key: e995b7fa13f3d9f946ff291512015444c90346ee68f0067f80037541a4b54d62.zip
      Description: /opt/kubectl/kubectl 1.33.0; /opt/helm/helm 3.18.0
      LicenseInfo: Apache-2.0
    Metadata:
      aws:cdk:path: ClusterStack/Kubectl/Resource
      aws:asset:path: asset.e995b7fa13f3d9f946ff291512015444c90346ee68f0067f80037541a4b54d62.zip
      aws:asset:is-bundled: false
      aws:asset:property: Content
  SwisscomEKSClusterKubectlHandlerRole0DF7DC5F:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/AmazonEC2ContainerRegistryPullOnly
        - Fn::If:
            - SwisscomEKSClusterHasEcrPublic2F4268D7
            - Fn::Join:
                - ""
                - - "arn:"
                  - Ref: AWS::Partition
                  - :iam::aws:policy/AmazonElasticContainerRegistryPublicReadOnly
            - Ref: AWS::NoValue
      Tags:
        - Key: ClusterType
          Value: EKS
        - Key: Environment
          Value: Production
        - Key: ManagedBy
          Value: CDK
        - Key: Project
          Value: SwisscomAssessment
    Metadata:
      aws:cdk:path: ClusterStack/SwisscomEKSCluster/KubectlHandlerRole/Resource
  SwisscomEKSClusterKubectlHandlerRoleDefaultPolicy01F6E471:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: eks:DescribeCluster
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - SwisscomEKSCluster27D1F5A0
                - Arn
          - Action: sts:AssumeRole
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - SwisscomEKSClusterCreationRoleC16F1072
                - Arn
        Version: "2012-10-17"
      PolicyName: SwisscomEKSClusterKubectlHandlerRoleDefaultPolicy01F6E471
      Roles:
        - Ref: SwisscomEKSClusterKubectlHandlerRole0DF7DC5F
    Metadata:
      aws:cdk:path: ClusterStack/SwisscomEKSCluster/KubectlHandlerRole/DefaultPolicy/Resource
  SwisscomEKSClusterControlPlaneSecurityGroup7B7327C7:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: EKS Control Plane Security Group
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      Tags:
        - Key: ClusterType
          Value: EKS
        - Key: Environment
          Value: Production
        - Key: ManagedBy
          Value: CDK
        - Key: Project
          Value: SwisscomAssessment
      VpcId:
        Fn::ImportValue: NetworkStack:ExportsOutputRefSwisscomVPC423AFC062A504B3F
    Metadata:
      aws:cdk:path: ClusterStack/SwisscomEKSCluster/ControlPlaneSecurityGroup/Resource
  SwisscomEKSClusterCreationRoleC16F1072:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS:
                - Fn::GetAtt:
                    - SwisscomEKSClusterKubectlHandlerRole0DF7DC5F
                    - Arn
                - Fn::GetAtt:
                    - awscdkawseksClusterResourceProviderNestedStackawscdkawseksClusterResourceProviderNestedStackResource9827C454
                    - Outputs.ClusterStackawscdkawseksClusterResourceProviderIsCompleteHandlerServiceRoleC5FDB7CBArn
                - Fn::GetAtt:
                    - awscdkawseksClusterResourceProviderNestedStackawscdkawseksClusterResourceProviderNestedStackResource9827C454
                    - Outputs.ClusterStackawscdkawseksClusterResourceProviderOnEventHandlerServiceRoleF1CFB156Arn
        Version: "2012-10-17"
      Tags:
        - Key: ClusterType
          Value: EKS
        - Key: Environment
          Value: Production
        - Key: ManagedBy
          Value: CDK
        - Key: Project
          Value: SwisscomAssessment
    Metadata:
      aws:cdk:path: ClusterStack/SwisscomEKSCluster/Resource/CreationRole/Resource
  SwisscomEKSClusterCreationRoleDefaultPolicyCC700C69:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: iam:PassRole
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - ClusterServiceRoleBFF38747
                - Arn
          - Action:
              - eks:CreateCluster
              - eks:CreateFargateProfile
              - eks:DeleteCluster
              - eks:DescribeCluster
              - eks:DescribeUpdate
              - eks:TagResource
              - eks:UntagResource
              - eks:UpdateClusterConfig
              - eks:UpdateClusterVersion
            Effect: Allow
            Resource:
              - arn:aws:eks:eu-west-1:737247133878:cluster/SwisscomCluster
              - arn:aws:eks:eu-west-1:737247133878:cluster/SwisscomCluster/*
          - Action:
              - eks:DeleteFargateProfile
              - eks:DescribeFargateProfile
            Effect: Allow
            Resource: arn:aws:eks:eu-west-1:737247133878:fargateprofile/SwisscomCluster/*
          - Action:
              - ec2:DescribeDhcpOptions
              - ec2:DescribeInstances
              - ec2:DescribeNetworkInterfaces
              - ec2:DescribeRouteTables
              - ec2:DescribeSecurityGroups
              - ec2:DescribeSubnets
              - ec2:DescribeVpcs
              - iam:CreateServiceLinkedRole
              - iam:GetRole
              - iam:listAttachedRolePolicies
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: SwisscomEKSClusterCreationRoleDefaultPolicyCC700C69
      Roles:
        - Ref: SwisscomEKSClusterCreationRoleC16F1072
    Metadata:
      aws:cdk:path: ClusterStack/SwisscomEKSCluster/Resource/CreationRole/DefaultPolicy/Resource
  SwisscomEKSCluster27D1F5A0:
    Type: Custom::AWSCDK-EKS-Cluster
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - awscdkawseksClusterResourceProviderNestedStackawscdkawseksClusterResourceProviderNestedStackResource9827C454
          - Outputs.ClusterStackawscdkawseksClusterResourceProviderframeworkonEvent74B2E770Arn
      Config:
        name: SwisscomCluster
        version: "1.33"
        roleArn:
          Fn::GetAtt:
            - ClusterServiceRoleBFF38747
            - Arn
        kubernetesNetworkConfig:
          ipFamily: ipv4
        resourcesVpcConfig:
          subnetIds:
            - Fn::ImportValue: NetworkStack:ExportsOutputRefSwisscomVPCWorkersSubnet1SubnetD75254CE334547A1
            - Fn::ImportValue: NetworkStack:ExportsOutputRefSwisscomVPCWorkersSubnet2SubnetB1A70A6E7EB74BF3
            - Fn::ImportValue: NetworkStack:ExportsOutputRefSwisscomVPCWorkersSubnet3SubnetE5472EB62D37FF91
          securityGroupIds:
            - Fn::GetAtt:
                - SwisscomEKSClusterControlPlaneSecurityGroup7B7327C7
                - GroupId
          endpointPublicAccess: true
          endpointPrivateAccess: true
        accessConfig:
          authenticationMode: API_AND_CONFIG_MAP
          bootstrapClusterCreatorAdminPermissions: true
      AssumeRoleArn:
        Fn::GetAtt:
          - SwisscomEKSClusterCreationRoleC16F1072
          - Arn
      AttributesRevision: 5
    DependsOn:
      - SwisscomEKSClusterCreationRoleDefaultPolicyCC700C69
      - SwisscomEKSClusterCreationRoleC16F1072
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: ClusterStack/SwisscomEKSCluster/Resource/Resource/Default
  SwisscomEKSClusterKubectlReadyBarrier1C39FEC4:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: aws:cdk:eks:kubectl-ready
    DependsOn:
      - SwisscomEKSClusterCreationRoleDefaultPolicyCC700C69
      - SwisscomEKSClusterCreationRoleC16F1072
      - SwisscomEKSCluster27D1F5A0
    Metadata:
      aws:cdk:path: ClusterStack/SwisscomEKSCluster/KubectlReadyBarrier
  SwisscomEKSClusterNodegroupWorkerNodes2451F550:
    Type: AWS::EKS::Nodegroup
    Properties:
      AmiType: AL2_x86_64
      CapacityType: ON_DEMAND
      ClusterName:
        Ref: SwisscomEKSCluster27D1F5A0
      DiskSize: 20
      ForceUpdateEnabled: true
      InstanceTypes:
        - m5.medium
      NodeRole:
        Fn::GetAtt:
          - NodeGroupRoleB2FF2978
          - Arn
      NodegroupName: Default
      ScalingConfig:
        DesiredSize: 2
        MaxSize: 5
        MinSize: 2
      Subnets:
        - Fn::ImportValue: NetworkStack:ExportsOutputRefSwisscomVPCWorkersSubnet1SubnetD75254CE334547A1
        - Fn::ImportValue: NetworkStack:ExportsOutputRefSwisscomVPCWorkersSubnet2SubnetB1A70A6E7EB74BF3
        - Fn::ImportValue: NetworkStack:ExportsOutputRefSwisscomVPCWorkersSubnet3SubnetE5472EB62D37FF91
      Tags:
        ClusterType: EKS
        Environment: Production
        ManagedBy: CDK
        Name: SwisscomEKS-WorkerNode
        NodeGroup: Default
        Project: SwisscomAssessment
    Metadata:
      aws:cdk:path: ClusterStack/SwisscomEKSCluster/NodegroupWorkerNodes/Resource
  SwisscomEKSClusterAwsAuthmanifest07BD5C83:
    Type: Custom::AWSCDK-EKS-KubernetesResource
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - awscdkawseksKubectlProviderNestedStackawscdkawseksKubectlProviderNestedStackResourceA7AEBA6B
          - Outputs.ClusterStackawscdkawseksKubectlProviderframeworkonEvent8D73200DArn
      Manifest:
        Fn::Join:
          - ""
          - - '[{"apiVersion":"v1","kind":"ConfigMap","metadata":{"name":"aws-auth","namespace":"kube-system","labels":{"aws.cdk.eks/prune-c80616e99a4c264a44fdee8354220cf379ce544d2b":""}},"data":{"mapRoles":"[{\"rolearn\":\"'
            - Fn::GetAtt:
                - NodeGroupRoleB2FF2978
                - Arn
            - \",\"username\":\"system:node:{{EC2PrivateDNSName}}\",\"groups\":[\"system:bootstrappers\",\"system:nodes\"]}]","mapUsers":"[]","mapAccounts":"[]"}}]
      ClusterName:
        Ref: SwisscomEKSCluster27D1F5A0
      RoleArn:
        Fn::GetAtt:
          - SwisscomEKSClusterCreationRoleC16F1072
          - Arn
      PruneLabel: aws.cdk.eks/prune-c80616e99a4c264a44fdee8354220cf379ce544d2b
      Overwrite: true
    DependsOn:
      - SwisscomEKSClusterKubectlReadyBarrier1C39FEC4
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: ClusterStack/SwisscomEKSCluster/AwsAuth/manifest/Resource/Default
  awscdkawseksClusterResourceProviderNestedStackawscdkawseksClusterResourceProviderNestedStackResource9827C454:
    Type: AWS::CloudFormation::Stack
    Properties:
      Tags:
        - Key: Environment
          Value: Production
        - Key: Project
          Value: SwisscomAssessment
      TemplateURL:
        Fn::Join:
          - ""
          - - https://s3.eu-west-1.
            - Ref: AWS::URLSuffix
            - /cdk-hnb659fds-assets-737247133878-eu-west-1/bd336dba84b1d2a6b231504e06d6f6fc3de7f100c1419e305048cb59ca30fb4b.json
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: ClusterStack/@aws-cdk--aws-eks.ClusterResourceProvider.NestedStack/@aws-cdk--aws-eks.ClusterResourceProvider.NestedStackResource
      aws:asset:path: ClusterStackawscdkawseksClusterResourceProviderFB371BF6.nested.template.json
      aws:asset:property: TemplateURL
  awscdkawseksKubectlProviderNestedStackawscdkawseksKubectlProviderNestedStackResourceA7AEBA6B:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        referencetoClusterStackKubectlA0ACB7D0Ref:
          Ref: Kubectl85A5A23F
        referencetoClusterStackSwisscomEKSClusterKubectlHandlerRoleDEE8582EArn:
          Fn::GetAtt:
            - SwisscomEKSClusterKubectlHandlerRole0DF7DC5F
            - Arn
        referencetoClusterStackSwisscomEKSClusterD5475F26ClusterSecurityGroupId:
          Fn::GetAtt:
            - SwisscomEKSCluster27D1F5A0
            - ClusterSecurityGroupId
      Tags:
        - Key: Environment
          Value: Production
        - Key: Project
          Value: SwisscomAssessment
      TemplateURL:
        Fn::Join:
          - ""
          - - https://s3.eu-west-1.
            - Ref: AWS::URLSuffix
            - /cdk-hnb659fds-assets-737247133878-eu-west-1/33e18418420f6d894ff79179935a38cb743761b239eb086979478616130c3441.json
    DependsOn:
      - SwisscomEKSClusterKubectlHandlerRoleDefaultPolicy01F6E471
      - SwisscomEKSClusterKubectlHandlerRole0DF7DC5F
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: ClusterStack/@aws-cdk--aws-eks.KubectlProvider.NestedStack/@aws-cdk--aws-eks.KubectlProvider.NestedStackResource
      aws:asset:path: ClusterStackawscdkawseksKubectlProviderA827E1EA.nested.template.json
      aws:asset:property: TemplateURL
  NodeGroupRoleB2FF2978:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/AmazonEKSWorkerNodePolicy
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/AmazonEKS_CNI_Policy
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      Tags:
        - Key: Environment
          Value: Production
        - Key: Project
          Value: SwisscomAssessment
    Metadata:
      aws:cdk:path: ClusterStack/NodeGroupRole/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/91W3U/bMBD/W5bHyQ3QbGjiaSFsCEFLVRAvqIpc+yheEzuynUIX9X/fOXGaMLYJNuBhD1Hs+/Dd/e7DHobVcO9juPuO3pkB48tBJuZhdWEpWxIkpZWgeVhNVQbXVUCNKXPgh+vgoAoKLSQTBc1ixlQpbXAQvA+Il3EKMbNCyZq8IUFOJV0An6hMMAEmOMDz+rR1rL3sbEPe1hTnl2rSmmgknI7nWsTi9kRmQsKWh7pPYHI+6lt9gh//Kt8z/aeQ/hrb7uyfj3w9DJ9t7D9SWWjqMnJdp6SF5E06gzybMdvMSHIjnVHSsGq32wRfKsd5lPfHZM5x+ljIQVrzAKfH5Nc+/xXJNVYNTBtiohQzBtaEsfvhPjws2RLsITVwPSMZzeechqhxRtegr0AbTCqBpQmrJCuNBY2JXDVkXwKsoY9pDp6iayDq5apg3eqinEtoHAtMvb5cF04Sy3KFbmNqSbAs58BsVttvi6y0txiRYNSV2EhxpxNPTtJ4fJQm5+OvJ8fpKJ6gJEheKCEtFikY49XnSlljNS18BIkGapWOeS7kBHQujIsGpa0ugQQcbmiZ2YQWlAm73hYjgjtG0wutyqJjtqWXCx9LfDZM7z/tp/sfHDZezvPOx+nRlxF6HTgzRmjgF+J7ixUXZtnb5vS+vxOyt5OtIz3UHW3aIW/pwnT9svUcofcJa8F9ec+FNJZKBk7XvHg0rp634ZD4zsRYHuQUy0ZjRYHBq0rcgLEbAmyILwxgpcZAjn30XUViHEyLohtb9dEP5PEemoJRpWbQjsb2m5G6hbDfFkIuSIKYqvx3wr/6miHmFdw6UZIL503tRv0wwsV5aYsSg9nFp9Nn/3baafp0kLkmGfiOGayiKDxt1ldRVDeQH0aTtb1VcicK9yI85ZsRYqBxhoscwmnz/wHp4jwZngkAAA==
    Metadata:
      aws:cdk:path: ClusterStack/CDKMetadata/Default
Conditions:
  SwisscomEKSClusterHasEcrPublic2F4268D7:
    Fn::Equals:
      - Ref: AWS::Partition
      - aws
Outputs:
  ClusterNameOutput:
    Value:
      Ref: SwisscomEKSCluster27D1F5A0
  ClusterEndpointOutput:
    Value:
      Fn::GetAtt:
        - SwisscomEKSCluster27D1F5A0
        - Endpoint
  ClusterArnOutput:
    Value:
      Fn::GetAtt:
        - SwisscomEKSCluster27D1F5A0
        - Arn
  KubeconfigUpdateCommand:
    Description: Run this command locally to configure kubectl access
    Value:
      Fn::Join:
        - ""
        - - "aws eks update-kubeconfig --name "
          - Ref: SwisscomEKSCluster27D1F5A0
          - " --region eu-west-1"
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]

